---@class EntityConnectionAnchor
---@field pos MapPosition
---@field dir defines.direction
---@field entity LuaEntity
---@field anchor_index integer

---@class AnchorPreviewData
---@field cursor_has_iopoint boolean
---@field nearest_anchor EntityConnectionAnchor?
---@field player_index integer
---@field render_ids integer[]